// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOwA2rgEl8L4V43v5SJQIfYD_ZdL0OtI',
    appId: '1:664978581793:android:bcf5d067948fdb0e017660',
    messagingSenderId: '664978581793',
    projectId: 'cord2-senior-design',
    storageBucket: 'cord2-senior-design.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAash_zoCB0XRfCW1iiLZz1m7usCMLJ9-g',
    appId: '1:664978581793:ios:57f9fb13de630837017660',
    messagingSenderId: '664978581793',
    projectId: 'cord2-senior-design',
    storageBucket: 'cord2-senior-design.appspot.com',
    androidClientId: '664978581793-qu98skff43dai5mqpnd1pcbd5u71i7th.apps.googleusercontent.com',
    iosClientId: '664978581793-hhiai0uleqpvu23sj2soh4ps7j38grbe.apps.googleusercontent.com',
    iosBundleId: 'com.cord.cord2MobileApp',
  );
}