// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbW3zcU-kZhfN2W5vBjYIyNQWniP9AKQw',
    appId: '1:571790127747:android:235897febcb103294c61b6',
    messagingSenderId: '571790127747',
    projectId: 'cord2-6c88c',
    databaseURL: 'https://cord2-6c88c-default-rtdb.firebaseio.com',
    storageBucket: 'cord2-6c88c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW7kjg-UUh-8nYEZC1iuyDFovkzSl8cc0',
    appId: '1:571790127747:ios:694bbb5e50643a7f4c61b6',
    messagingSenderId: '571790127747',
    projectId: 'cord2-6c88c',
    databaseURL: 'https://cord2-6c88c-default-rtdb.firebaseio.com',
    storageBucket: 'cord2-6c88c.firebasestorage.app',
    iosClientId: '571790127747-25f4gtg81jc0j1tsfejuvknad7pon6bo.apps.googleusercontent.com',
    iosBundleId: 'com.cord.cord2MobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW7kjg-UUh-8nYEZC1iuyDFovkzSl8cc0',
    appId: '1:571790127747:ios:694bbb5e50643a7f4c61b6',
    messagingSenderId: '571790127747',
    projectId: 'cord2-6c88c',
    storageBucket: 'cord2-6c88c.firebasestorage.app',
    iosBundleId: 'com.cord.cord2MobileApp',
  );

}